@startuml

title __MODELO's Class Diagram__\n

  namespace com.example.realbreadbeta {
    namespace modelo {
      class com.example.realbreadbeta.modelo.Categorias {
          ~ imagen : Integer
          ~ nombre : String
          + Categorias()
          + getImagen()
          + getNombre()
          + setImagen()
          + setNombre()
      }
    }
  }
  

  namespace com.example.realbreadbeta {
    namespace modelo {
      class com.example.realbreadbeta.modelo.Ofertas {
          ~ urlImagen : Integer
          + Ofertas()
          + getUrlImagen()
          + setUrlImagen()
      }
    }
  }
  

  namespace com.example.realbreadbeta {
    namespace modelo {
      class com.example.realbreadbeta.modelo.Productos {
          ~ descripcion : String
          ~ nombre : String
          ~ precio : String
          ~ urlImagen : Integer
          + Productos()
          + getDescripcion()
          + getNombre()
          + getPrecio()
          + getUrlImagen()
          + setDescripcion()
          + setNombre()
          + setPrecio()
          + setUrlImagen()
      }
    }
  }
  

  namespace com.example.realbreadbeta {
    namespace modelo {
      class com.example.realbreadbeta.modelo.ProductosDeCategoria {
          ~ descripcion : String
          ~ nombre : String
          ~ precio : String
          ~ primeraImagen : Integer
          ~ segundaImagen : Integer
          ~ terceraImagen : Integer
          + ProductosDeCategoria()
          + getDescripcion()
          + getNombre()
          + getPrecio()
          + getPrimeraImagen()
          + getSegundaImagen()
          + getTerceraImagen()
          + setDescripcion()
          + setNombre()
          + setPrecio()
          + setPrimeraImagen()
          + setSegundaImagen()
          + setTerceraImagen()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
